#!/usr/bin/env bash
session="$HOME/.sessionizer"
# Session will have
# - prev_session
# - curr_session

if [[ $# -eq 1 ]]; then
    selected=$1
else
    source "$session"
    findres=$(find ~/dev ~/.config -mindepth 1 -maxdepth 1 -type d; find ~/dotfiles -prune )

    if [[ -n $prev_state ]]; then
        selected=$((echo "$prev_state" && echo "$findres") | fzf)
    else
        selected=$(echo "$findres" | fzf)
    fi
fi

if [[ -z $selected ]]; then
    exit 0
fi

echo "curr_state=$selected" > "$session"
echo "prev_state=$curr_state" >> "$session"

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -n $TMUX ]]; then
    echo "INSIDE"
    tmux switch-client -t $selected_name
else
    echo "OUTSIDE"
    tmux attach -t $selected_name
fi


